#!/bin/sh
#
# An example hook script to prepare a packed repository for use over
# dumb transports.
#
# To enable this hook, make this file executable by "chmod +x post-update".

git-update-server-info

git reset --hard HEAD

# run sync-modules.sh after each push
if (cd modules; test -x sync-modules.sh >/dev/null); then
  (cd modules && ./sync-modules.sh)
fi
